# Generated by Django 5.1 on 2024-08-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='slug',
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
            preserve_default=False,
        ),
    ]
